### ISSUE TITLE
/usr/bin/env: node: No such file or directory

### ISSUE THREAD

**Issue by jtmeng** [skygragon/leetcode-cli#23]
Hello, 
      I have successfully installed leetcode-cli.  Then when I run "leetcode list" or "leetcode help", the command failed with "/usr/bin/env: node: No such file or directory". 
     Do you know what's wrong here? 
     Thanks. 

Jintao

**Comment by skygragon** [comment]
which OS r u using, and which version of node is installed? It seems the 'node' binary can't be found in your PATH?

**Comment by skygragon** [comment]
@jtmeng any update on this?

**Comment by stefanwade** [comment]
Hello, 
I met the same question, do u know how to solve this problem?
Thanks.

stefan

**Comment by stefanwade** [comment]
my os version is ubuntu 14.04, node is v0.10.25

**Comment by skygragon** [comment]
I guess the problem is: ubuntu 14.04 is using "nodejs" as the binary name instead of "node" (already taken by another package), so please try to install "nodejs-legacy" package to fix this naming issue.

Well I recommend you to install the latest nodejs (https://nodejs.org/en/) for the long term running.

**Comment by stefanwade** [comment]
it works，thanks very mush. @skygragon
