### ISSUE TITLE
Some questions about the code

### ISSUE THREAD

**Issue by aaaahern** [skygragon/leetcode-cli#3]
Hi, I found this tool on 1point3acres and I'm interested in improving it. 

Since leetcode change their URL for problem list, your PROBLEM_URL is not working now. I figured out the new API URL and made some change.

Besides, I have two questions about your implementation:
1. Why do you need to store the password as plain text in local file? Since we have the session id and other information which can keep login, it that still necessary?
2. I notice that you cache all the problems in local file including the status of each problem. Once you store it, it will never be updated, include the status.

**Comment by aaaahern** [comment]
oh I see when you update the cache

**Comment by skygragon** [comment]
Thanks again man! Now the 'list' is fixed to support this new leetcode api. Later will release it out.

As the password thing, in the very beginning I was thinking of supporting auto re-login when the session expired, thus the password is needed. You see leetcode will expire the previous session if new one is created. For example when you login on web page, the cli session will get expired immediately. That's why re-login is needed otherwise 403 forbidden will occur as #2 issue said.

While now I'm more preferring another option that to NOT save password in file for the sake of security, instead we can prompt login again in case of session expired. Please let me your idea about this.
