### ISSUE TITLE
socket hang up when test or submit in ubuntu16.04

### ISSUE THREAD

**Issue by dreamsuifeng** [skygragon/leetcode-cli#38]
RT.

**Comment by skygragon** [comment]
Could you give more details?

Before submit please try followings to see if your problem is gone:

1. login agian:
```
leetcode login -l
```

2. run the latest code:
```
cd <your local repo>
git pull --rebase origin master
./bin/install	// install globally, OR
./bin/leetcode <command>	// run the command locally
```

### Problem Summary
describe what's going wrong

### How to reproduce
more details will help a lot, e.g.
1. which command failed, what parameters used
2. actual/expected output
3. if possible, run command with "-vv" will give more outputs of the HTTP data, do REMEMBER to delete your cookies before paste here!!

### Environment
if using latest code, you could get those info in `leetcode version -v`

- OS version:
- Node version:
- Npm version:

**Comment by dreamsuifeng** [comment]
Sorry, I'm a newer of github. The problem is solved, it happened because of the network problem, today is ok, thank u very much. The leetcode-cil is very good and convenient.
