### ISSUE TITLE
Is there an option to change the name of the generated file

### ISSUE THREAD

**Issue by fuermosi777** [skygragon/leetcode-cli#46]
### Problem Summary
Currently run `leetcode show xx -g -x` it will generate a file named "xx.xxx-xx-xx.java". However, Intellij IDEA will throw an error:

`Error:(1, 8) java: class Solution is public, should be declared in a file named Solution.java`.

Is there an option so that user can generate a file named "Solution.java"?

Thanks!

**Comment by skygragon** [comment]
@fuermosi777 Personally I would strongly recommend you use other light-weight text editors instead of those IDEs like eclipse or IDEA. The purpose of leetcode-cli is trying to boost your coding experience beyond leetcode.com, but still obey the principle to keep you away from the dependency on the IDEs. See http://www.jianshu.com/p/48295edbf42e if helps.

**Comment by fuermosi777** [comment]
Thanks
