### ISSUE TITLE
[Feature Request] Python3 support

### ISSUE THREAD

**Issue by jarronshih** [skygragon/leetcode-cli#55]
Due to there's some syntax different between python2 and python3, I think we should have lang `python3`.

**Comment by ocavue** [comment]
I don't think that using [`.py3`](https://github.com/skygragon/leetcode-cli/commit/b7c46fea46136d6b3dd210575a11a229cd2e7025#diff-edd552e5b38c38c77f6df11eb7b22ebeR90) is a good idea. 

`.py3` is not an official Python extension and both python2 and python3 use `.py` as the extension. That means most Python IDE can't display `file.py3` correctly. The best way to distinguish between python2 and python3 is comments of the first line comment (like bash). So My suggestion is to automatically add `#! Python2` or `#! Python3` at the top of the file to mark the type of python file.

I can help develop this feature if you agree with this idea. @skygragon

**Comment by jarronshih** [comment]
I think `#!python2` or `#!python3` is a good idea. So much better than using *.py3 !

**Comment by skygragon** [comment]
Yep, I was considering using shabang at first but finally decided not to go right now due to following considerations:

1. the first line is not always guaranteed, e.g. existing command like 'submission' might add other comments in the head of file. So we also need to enhance submission/show commands as to respect this feature.
2. I was expecting modern IDEs to be smart enough or at least configurable to recognize other filetype (e.g. like VIM), while seems it turns out not to be.
3. You see one very important consideration of leetcode is to NOT use any heavy IDE thus to train our abilities to write bare code from scratch on papers or whiteboards, so any sugar features to make IDE experience happier should not be our first priorities.

So finally for the time being I chose the easier way (also the right way I think) to make things work. Hope this tradeoff makes a bit sense to your guys.

**Comment by shihan9** [comment]
yes, there is no need to put shebang at the first line of files generated by leetcode-cli, because we are not telling leetcode's interpreter which python version we are using. leetcode-cli decides python version by peeking at the `lcconfig` or the command line argument when generating python files, and infers python version by file extension when `leetcode test` or `leetcode submit`. my suggestion is, on the contrary, to respect the `lcconfig` or the command line argument passed in when run `leetcode submit` or `leetcode test`. to make my point clearer, here are two gists:
1. `leetcode show -g`, generating files according to cml argument or `lcconfig`, as it is now. the only difference is generating python files all in `.py` file extension.
2. `leetcode test` or `leetcode submit`: look at `lcconfig` when file has '.py' as extension.

`py3` kinda breaking common sense. looking forward to your reply.

**Comment by skygragon** [comment]
@shihan9 the config way sounds like a doable solution while it might involve further user activities (not a one-time effort) to manually take care of python3 stuff by themselves. It would be better if we could make the this more transparent to user experience and do the magic behind the curtain.

To achieve this we have to persistent the python3 flag somewhere. The config is one option while it affects global scope. The generated source file is a better one due to its natural file level scope. One feasible way is encode the python3 flag into the filename as below, just as what we did for question id and slug, e.g.
- for python 2.x, uses 1.two-sum.py
- for python 3, uses 1.two-sum.python3.py

The `test` and `submit` command could easily decode the filename to know whether we should use python or python3 in the context.

**Comment by shihan9** [comment]
@skygragon the filename way sounds like a workaround. thanks for reply. i still consider config way being better :).

**Comment by yzyDavid** [comment]
for shebang line, I think `#!/usr/bin/env python3` would be better.

**Comment by skygragon** [comment]
Now latest version is using embedded meta within file content, instead of file name.
