### ISSUE TITLE
Is that possible to list questions with Topics like "Dynamic Programming"?

### ISSUE THREAD

**Issue by ajing** [skygragon/leetcode-cli#76]
Just wonder

**Comment by skygragon** [comment]
Currently we can't.

Because there is no tags (e.g. tagged as "array" or "dynamic programming") returned in the problem list API. To collect those tags we have to go through all the problems and crawl each problem page in the beginning. At the time of writing we have 700+ problems out there, so it would cost a while to fetch all the data...

**Comment by skygragon** [comment]
@ajing feel free to try the latest 'company' plugin that supports both filtering questions by company and tags. You need to update leetcode-cli as well.
```
$ npm install -g skygragon/leetcode-cli
$ leetcode plugin -i company
$ leetcode list -t google -t tree
```

**Comment by ajing** [comment]
awesome! thanks!
