### ISSUE TITLE
File name should match class name

### ISSUE THREAD

**Issue by gynet** [skygragon/leetcode-cli#78]
Currently, each file got named as "[problem].java". However, they use "Solution" as the class name in the content.

 Is that better to change the file name to be "Solution.java" to keep it matching the class name?
 Otherwise, the java file is not compilable... 

 I think we can put each problem into a separate folder named the same as the problem.

**Comment by skygragon** [comment]
Yep this because the code we generated is not a code snippet, instead of a complete source file that could be run or compiled locally. That's exactly what leetcode.com need.

That's why 3rd party plugins are provided to fulfill advanced requirement, e.g. [this plugin](https://github.com/skygragon/leetcode-cli-plugins/blob/master/docs/cpp.run.md) is used to run c++ code locally without sending it to leetcode.com.

**Comment by gynet** [comment]
Any plan for Java?

**Comment by skygragon** [comment]
move to https://github.com/skygragon/leetcode-cli-plugins/issues/5
