### ISSUE TITLE
how do I update problems list 

### ISSUE THREAD

**Issue by raghumaddali** [skygragon/leetcode-cli#79]
@skygragon Is there a way to update the problems set or problems.json so I get updated list of questions by company??

**Comment by skygragon** [comment]
what do you mean "by company"?

**Comment by raghumaddali** [comment]
updated questions grouped by company. when we do "leetcode list -t google"

On Dec 12, 2017 9:45 PM, "skygragon" <notifications@github.com> wrote:

what do you mean "by company"?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/skygragon/leetcode-cli/issues/79#issuecomment-351265028>,
or mute the thread

**Comment by skygragon** [comment]
@raghumaddali currently this company filtering feature is only supported via [company plugin](https://github.com/skygragon/leetcode-cli-plugins/blob/master/docs/company.md). It will not touch problems.json at all.

**Comment by raghumaddali** [comment]
@skygragon thank you. I have company plugin installed and  "leetcode list -t google" returns around 185 problems. My questions is more of updated list as I see leetcode site has 224 questions tagged under "Google" and other blogs has around 215 listed. Sorry, if I was not clear.

Another dumb question, I see the frequency (percentage) of a problem (e.g: [1]Two Sum  Easy(36.36%)) is same for different companies. Is this expected?

**Comment by skygragon** [comment]
Yep this count gap is expected since "company" plugin is just a hardcoded list by the time writing, it can't know any new questions from leetcode.com. You see on leetcode.com this company information is treated as a kind of bonus for paid user only. That's why I create an individual plugin for it since its data is manually collected from internet thus not 100% accurate :)

As for the percentage number, it means: x = "# accepted of all users" / "# submit of all users", not related to company from my understanding.

**Comment by skygragon** [comment]
moved to https://github.com/skygragon/leetcode-cli-plugins/issues/6

need update "company" plugin to latest
